config/routes.rb
Monofonia::Application.routes.draw do
  match 'group/create' => 'group#create', :via => [:get, :post]
  get "user/logout"
  match 'user/signup' => 'user#signup', :via => [:get, :post]
  match 'user/login' => 'user#login', :via => [:get, :post]
  get "group/show"

  root :to => "home#index" # The main head
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :users
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  validates_length_of :username, :within => 3..40
  validates_length_of :pass, :within => 5..40
  validates_presence_of :username, :pass, :salt
  validates_uniqueness_of :username

  attr_protected :id, :salt

  attr_accessor :pass

  has_and_belongs_to_many :groups

  def pass=(pass)
    return if self.password
    if pass
      @pass = pass
    else
      @pass = ""
    end
    self.salt = User.random_string(10) if !self.salt?
    self.password = User.encrypt(@pass, self.salt)
  end

  def self.authenticate(username, pass)
    u = find(:first, :conditions => ["username = ?", username])
    return nil if u.nil?
    return u if User.encrypt(pass, u.salt) == u.password
  end

  def self.random_string(len)
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) do |i|
      newpass << chars[rand(chars.size-1)]
    end
    return newpass
  end

  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest(pass+salt)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def create
    @group = Group.new(params[:group])
    respond_to do |format|
      if @group.save
        User.find(session[:cur_user_id]).groups << @group
        format.html {redirect_to root_url}
        format.json {head :no_content}
      else
        format.html {render :action => "create"}
        @group.errors.clear if !request.post?
        format.json {render :json => @group.errors}
      end
    end
  end
  def index
    @groups = @_current_user.groups if @_current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @_current_user = session[:cur_user_id] && User.find(session[:cur_user_id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def signup
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        session[:cur_user_id] = User.authenticate(@user.username, @user.pass).id
        puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@22"
        format.html {redirect_to root_url}
        format.json {head :no_content}
      else
        format.html {render :action => "signup"}
        @user.errors.clear if !request.post?
        format.json {render :json => @user.errors}
      end
    end
  end

  def login
    if request.post?
      if session[:cur_user_id] = User.authenticate(params[:user][:username], params[:user][:pass]).id
        redirect_to root_url
      else
      end
    end
  end

  def logout
    session[:cur_user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/group/create.html.haml
= form_for @group, :url => {:action => "create"} do |f|
  - if @group.errors.any?
    - @group.errors.full_messages.each do |msg|
      = msg
  = f.text_field :name, :size => 20
  %br
  = f.submit "Create"

app/views/group/index.html.haml
- if @_current_user

app/views/home/index.html.haml
%strong Hello and welcome to monofonia

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Monofonia
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .header
      = render "shared/header"
    .contents
      = yield
    .userControl
      - if @_current_user
        = render "user/control_panel"
      - else
        = render "user/login_panel"

app/views/shared/_header.html.haml
.header
  Monofonia

app/views/user/_control_panel.html.haml
.control_panel
  = link_to 'Logout', user_logout_url

app/views/user/_login_panel.html.haml
= form_tag :controller => "user", :action => "login" do
  .loginHeader
    Login
  = label_tag "Username: "
  = text_field "user", "username", :size => 15
  %br
  = label_tag "Password: "
  = password_field "user", "pass", :size => 15
  %br
  = submit_tag "submit"
  %br
  = link_to 'Register', user_signup_url

app/views/user/login.html.haml
%p#notice= notice
= form_tag :controller => "user", :action => "login" do
  %h3 login
  = text_field "user", "username", :size => 20
  %br
  = password_field "user", "pass", :size => 20
  %br
  = submit_tag "submit"
  %br
  = link_to 'Register', user_signup_url

app/views/user/signup.html.haml
= form_for @user, :url => {:action => "signup"} do |f|
  - if @user.errors.any?
    - @user.errors.full_messages.each do |msg|
      = msg
  = f.text_field :username, :size => 20
  %br
  = f.password_field :pass, :size => 20
  %br
  = f.submit "Signup"